ALTER TABLE "Visit" ADD COLUMN "clinicallyClosedAt" TIMESTAMP(3);
ALTER TABLE "PatientIdentityReconciliation" ADD COLUMN "previousData" JSONB,
  ADD COLUMN "resultingData" JSONB, ADD COLUMN "reversedAt" TIMESTAMP(3);
ALTER TABLE "VisitCancellation" DROP CONSTRAINT "VisitCancellation_reasonCode_check";
ALTER TABLE "VisitCancellation" ADD CONSTRAINT "VisitCancellation_reasonCode_check" CHECK ("reasonCode" IN (
  'PATIENT_REQUEST', 'PATIENT_LEFT_BEFORE_CARE', 'OVERDUE_UNPROCESSED', 'DUPLICATE_VISIT', 'WRONG_PATIENT',
  'CLINIC_UNAVAILABLE', 'SERVICE_UNAVAILABLE', 'CLINICAL_REDIRECTION',
  'SHA_BENEFIT_OR_ELIGIBILITY', 'PRIVATE_COVER_NOT_AVAILABLE', 'CREATED_IN_ERROR', 'OTHER'
));
