"use client";
import { useEffect, useState } from "react";
import { jsonRequest } from "@/lib/client-http";
import StaffWorkstation from "@/components/StaffWorkstation";
import CatalogManager from "@/components/CatalogManager";
import ImportCenter from "@/components/ImportCenter";
import type { StockFocus } from "@/components/InventoryWorkstation";
import GovernancePanel from "@/components/GovernancePanel";
import IdentityProviderPanel from "@/components/IdentityProviderPanel";
import MedicationSafetyPanel from "@/components/MedicationSafetyPanel";
import DataQualityPanel from "@/components/DataQualityPanel";
import OperationsEvidencePanel from "@/components/OperationsEvidencePanel";
import ShaContractReadinessPanel from "@/components/ShaContractReadinessPanel";

type StockAction = { issue: "LOW_STOCK" | "EXPIRING"; catalogItemId: string; batchId?: string | null; code: string; name: string; detail: string };
type Overview = { metrics: Record<string, number>; actionItems: { stock: StockAction[] }; sessions: { id: string; userAgent: string | null; lastSeenAt: string; expiresAt: string; user: { displayName: string; email: string } }[]; audits: { id: string; action: string; entityType: string; entityId: string; reason: string | null; occurredAt: string; user: { displayName: string } | null }[]; operations: { environment: string; release: string; databaseLatencyMs: number; audit: { sequence: string; updatedAt: string | null }; configuration: { ready: boolean; checks: { code: string; ready: boolean }[] }; governance: { approved: number; total: number; ready: boolean } } };
const labels: Record<string, string> = { registeredToday: "Patients registered today", waiting: "Patients waiting now", visitsToday: "Visits today", activeStaff: "Active staff accounts", outstanding: "Outstanding bills (KES)", pendingClaims: "Claims requiring action", pendingOrders: "Purchase approvals", lowStock: "Low-stock medicines", expiringStock: "Expiring within 90 days", activeSessions: "Active login sessions" };

type Tab = "overview" | "quality" | "evidence" | "governance" | "sha" | "access" | "identity" | "safety" | "catalogue" | "imports";
type Integration = { key: string; name: string; state: "AVAILABLE" | "PREPARED_ON_HOLD" | "NOT_CONFIGURED"; purpose: string; reason: string; requirements: string[] };
export default function AdminCenter({ permissions, onOpenStock }: { permissions: string[]; onOpenStock: (focus: StockFocus) => void }) {
  const [data, setData] = useState<Overview | null>(null); const [error, setError] = useState("");
  const [integrations, setIntegrations] = useState<Integration[]>([]);
  const [tab, setTab] = useState<Tab>("overview");
  const canAudit = permissions.includes("audit.view");
  useEffect(() => { void Promise.all([jsonRequest<Overview>("/api/admin/overview", undefined, "Administration dashboard could not be loaded"), jsonRequest<{ integrations: Integration[] }>("/api/admin/integrations", undefined, "Integration readiness could not be loaded")]).then(([overview, readiness]) => { setData(overview); setIntegrations(readiness.integrations); }).catch(reason => setError(reason.message)); }, []);
  const tabs: { key: Tab; label: string }[] = [{ key: "overview", label: "Overview" }, { key: "quality", label: "Data quality" }, ...(permissions.includes("admin.operations") ? [{ key: "evidence" as Tab, label: "Operations evidence" }] : []), { key: "governance", label: "Release gates" }, { key: "sha", label: "SHA readiness" }, ...(permissions.includes("admin.clinical_safety") ? [{ key: "safety" as Tab, label: "Medication safety" }] : []), ...(permissions.includes("admin.users") ? [{ key: "access" as Tab, label: "Users & access" }, { key: "identity" as Tab, label: "Workforce identity" }] : []), ...(permissions.includes("admin.catalog") ? [{ key: "catalogue" as Tab, label: "Services & pricing" }, { key: "imports" as Tab, label: "Data imports" }] : [])];
  return <><header><div><p className="eyebrow">Administration</p><h1>Facility control centre</h1><p>Manage operations, access, services and governance from one place.</p></div></header><nav className="workspaceTabs" aria-label="Administration sections">{tabs.map(item => <button className={tab === item.key ? "active" : ""} onClick={() => setTab(item.key)} key={item.key}>{item.label}</button>)}</nav>{tab === "quality" && <DataQualityPanel/>}{tab === "evidence" && <OperationsEvidencePanel/>}{tab === "governance" && <GovernancePanel canEdit={permissions.includes("admin.assign_governance")} />}{tab === "sha" && <ShaContractReadinessPanel canEdit={permissions.includes("admin.assign_governance")} />}{tab === "safety" && <MedicationSafetyPanel/>}{tab === "access" && <div className="embeddedWorkspace"><StaffWorkstation/></div>}{tab === "identity" && <IdentityProviderPanel/>}{tab === "catalogue" && <div className="embeddedWorkspace"><CatalogManager/></div>}{tab === "imports" && <div className="embeddedWorkspace"><ImportCenter/></div>}{tab === "overview" && <>{error && <div className="alert">{error}</div>}{!data ? !error && <section className="card"><p>Loading administration controls…</p></section> : <>
    <section className="metricGrid">{Object.entries(data.metrics).map(([key, value]) => <article className={`metric ${["pendingClaims", "pendingOrders", "lowStock", "expiringStock"].includes(key) && value ? "urgent" : ""}`} key={key}><span>{labels[key] || key}</span><strong>{key === "outstanding" ? value.toLocaleString() : value}</strong></article>)}</section>
    <section className="card"><div className="cardHead"><div><h2>Operational health evidence</h2><p>Runtime identity, database response, audit-chain progress and release gates.</p></div><span className={`statusPill ${data.operations.configuration.ready && data.operations.governance.ready ? "done" : "waiting"}`}>{data.operations.environment}</span></div><div className="summaryGrid"><div className="summaryLine"><strong>Release</strong><span>{data.operations.release}</span></div><div className="summaryLine"><strong>Database dashboard query</strong><span>{data.operations.databaseLatencyMs} ms</span></div><div className="summaryLine"><strong>Audit-chain head</strong><span>event {data.operations.audit.sequence}</span></div><div className="summaryLine"><strong>Governance evidence</strong><span>{data.operations.governance.approved}/{data.operations.governance.total} approved</span></div>{data.operations.configuration.checks.map(check => <div className="summaryLine" key={check.code}><strong>{check.code.replaceAll("_", " ")}</strong><span>{check.ready ? "Ready" : "Pending"}</span></div>)}</div></section>
    <div className="supplyGrid"><section className="card"><div className="cardHead"><div><h2>Stock requiring action</h2><p>Select an item to open its inventory record and correct the expiry when needed.</p></div></div><div className="queue">{data.actionItems.stock.slice(0, 12).map(item => <button type="button" className="row stockAction" onClick={() => onOpenStock({ catalogItemId: item.catalogItemId, batchId: item.batchId })} key={`${item.issue}-${item.catalogItemId}-${item.batchId || "item"}`}><span className="dot"/><div><strong>{item.name}</strong><small>{item.issue.replaceAll("_", " ")} · {item.detail}</small></div><b>Open stock</b></button>)}{!data.actionItems.stock.length && <p>No current stock exceptions.</p>}</div></section>
      <section className="card"><div className="cardHead"><div><h2>Access oversight</h2><p>Current sessions; disable a staff account to revoke access immediately.</p></div><strong>{data.sessions.length}</strong></div><div className="queue">{data.sessions.map(session => <div className="row" key={session.id}><span className="dot"/><div><strong>{session.user.displayName}</strong><small>{session.user.email} · last seen {new Date(session.lastSeenAt).toLocaleString()}</small></div></div>)}</div></section></div>
    <details className="card managementPanel"><summary><span><strong>External integration readiness</strong><small>Certification and API connection status</small></span><b>{integrations.length}</b></summary><div className="queue managementBody">{integrations.map(item => <div className="row" key={item.key}><span className="dot"/><div><strong>{item.name} · {item.state.replaceAll("_", " ")}</strong><small>{item.purpose} · {item.reason}</small>{item.requirements.length > 0 && <small>Pending: {item.requirements.join("; ")}</small>}</div></div>)}</div></details>
    {canAudit && <details className="card managementPanel"><summary><span><strong>Recent audit trail</strong><small>Facility-scoped, serialized and tamper-evident records</small></span><b>{data.audits.length}</b></summary><div className="queue managementBody">{data.audits.map(event => <div className="row" key={event.id}><span className="dot"/><div><strong>{event.action.replaceAll("_", " ")}</strong><small>{event.user?.displayName || "System"} · {event.entityType} · {new Date(event.occurredAt).toLocaleString()}{event.reason ? ` · ${event.reason}` : ""}</small></div><code>{event.entityId.slice(0, 8)}</code></div>)}<a className="secondary" href="/api/admin/audit/export">Download verified audit export</a></div></details>}
  </>}</>}</>;
}
