"use client";

import { type FormEvent, useCallback, useEffect, useState } from "react";
import { jsonRequest } from "@/lib/client-http";

type Patient = { id: string; patientNumber: string; fullName: string };
type Rights = { id: string; requestNumber: string; type: string; status: string; dueAt: string; patient: Patient };
type Exchange = { id: string; channel: string; kind: string; status: string; profileVersion: string; attemptCount: number; errorMessage?: string | null };

function PatientPicker({ onSelect }: { onSelect: (patient: Patient) => void }) {
  const [query, setQuery] = useState(""); const [matches, setMatches] = useState<Patient[]>([]);
  useEffect(() => { const timer = window.setTimeout(() => { if (query.trim().length < 2) return setMatches([]); void jsonRequest<{ patients: Patient[] }>(`/api/patients?q=${encodeURIComponent(query)}`).then(({ patients }) => setMatches(patients)); }, 250); return () => window.clearTimeout(timer); }, [query]);
  return <label className="wide">Find patient<input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name or patient number" />{matches.map((item) => <button className="patientResult" type="button" key={item.id} onClick={() => { onSelect(item); setQuery(item.fullName); setMatches([]); }}><strong>{item.fullName}</strong><span>{item.patientNumber}</span></button>)}</label>;
}

export default function CertificationWorkflowsPanel() {
  const [rights, setRights] = useState<Rights[]>([]); const [exchanges, setExchanges] = useState<Exchange[]>([]); const [patient, setPatient] = useState<Patient | null>(null);
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const [r, e] = await Promise.all([jsonRequest<{ requests: Rights[] }>("/api/admin/patient-rights"), jsonRequest<{ submissions: Exchange[] }>("/api/admin/exchange")]); setRights(r.requests); setExchanges(e.submissions); }, []);
  useEffect(() => { void load().catch((reason) => setError(reason.message)); }, [load]);
  async function act(url: string, body: object, message: string) { setBusy(true); setError(""); setNotice(""); try { await jsonRequest(url, { method: "POST", body: JSON.stringify(body) }); setNotice(message); await load(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  function createRights(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!patient) return setError("Select a patient"); const form = new FormData(event.currentTarget); void act("/api/admin/patient-rights", { action: "CREATE", patientId: patient.id, type: form.get("type"), channel: form.get("channel"), details: form.get("details") }, "Patient-rights request recorded with a due date and audit trail."); }
  function prepare(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const channel = String(form.get("channel")); let payload: object | undefined; try { payload = channel === "PUBLIC_HEALTH" ? JSON.parse(String(form.get("payload") || "{}")) : undefined; } catch { return setError("Public-health payload must be valid JSON"); } void act("/api/admin/exchange", { action: "PREPARE", channel, kind: form.get("kind"), profileVersion: form.get("profileVersion"), ...(channel === "DHA_FHIR" ? { patientId: patient?.id } : { payload }) }, "Exchange payload prepared; delivery stays gated until approvals and transport are configured."); }
  return <div className="embeddedWorkspace">{error && <div className="alert">{error}</div>}{notice && <div className="alert success">{notice}</div>}
    <section className="card"><h2>Identity review</h2><p>Use the dedicated Patient identity review and corrections panel on the care dashboard. It has its own patient selection and reversible correction history.</p></section>
    <section className="card"><div className="cardHead"><div><h2>Patient-rights requests</h2><p>Track access, correction, restriction, portability and objection requests.</p></div><strong>{rights.filter((item) => !["COMPLETED", "DENIED", "CANCELLED"].includes(item.status)).length} open</strong></div><form className="dataForm" onSubmit={createRights}><PatientPicker onSelect={setPatient}/><label>Request type<select name="type"><option>ACCESS</option><option>CORRECTION</option><option>RESTRICTION</option><option>PORTABILITY</option><option>OBJECTION</option></select></label><label>Channel<select name="channel"><option>IN_PERSON</option><option>EMAIL</option><option>LETTER</option><option>PHONE</option><option>PORTAL</option></select></label><label className="wide">Request details<textarea name="details" required minLength={10} /></label><button className="primary" disabled={busy}>Open request</button></form><div className="queue compact">{rights.map((item) => <div className="row" key={item.id}><span className="dot"/><div><strong>{item.requestNumber} · {item.patient.fullName}</strong><small>{item.type} · {item.status} · due {new Date(item.dueAt).toLocaleDateString()}</small></div>{item.status === "RECEIVED" && <button className="secondary" disabled={busy} onClick={() => void act("/api/admin/patient-rights", { action: "UPDATE", id: item.id, status: "IN_REVIEW" }, "Request moved to review.")}>Start review</button>}</div>)}</div></section>
    <section className="card"><div className="cardHead"><div><h2>National exchange outbox</h2><p>Prepare versioned, hashed payloads. Sending requires approved evidence and explicitly enabled transport.</p></div></div><form className="dataForm" onSubmit={prepare}><label>Channel<select name="channel"><option>DHA_FHIR</option><option>PUBLIC_HEALTH</option></select></label><label>Dataset/resource kind<input name="kind" required defaultValue="PATIENT" /></label><label>Profile or dataset version<input name="profileVersion" required /></label><PatientPicker onSelect={setPatient}/><label className="wide">Public-health JSON payload<textarea name="payload" defaultValue="{}" /></label><button className="primary" disabled={busy}>Prepare submission</button></form><div className="queue compact">{exchanges.map((item) => <div className="row" key={item.id}><span className="dot"/><div><strong>{item.channel.replaceAll("_", " ")} · {item.kind}</strong><small>{item.status} · profile {item.profileVersion} · {item.attemptCount} attempt(s){item.errorMessage ? ` · ${item.errorMessage}` : ""}</small></div>{["PREPARED", "FAILED", "REJECTED"].includes(item.status) && <button className="secondary" disabled={busy} onClick={() => void act("/api/admin/exchange", { action: "SEND", id: item.id }, "Submission sent and acknowledgement retained.")}>Send</button>}</div>)}</div></section>
  </div>;
}
