"use client";
import { useEffect, useState } from "react";
import { jsonRequest } from "@/lib/client-http";

type PatientRef = { id: string; patientNumber: string; fullName: string };
type Data = { summary: Record<string, number>; issues: { duplicates: { key: string; patients: PatientRef[] }[]; missingContacts: PatientRef[]; missingAge: PatientRef[]; missingConsent: PatientRef[]; incompleteVisits: { id: string; visitNumber: string; status: string; arrivedAt: string; flags: string[]; patient: Omit<PatientRef, "id"> }[]; delayedResults: { id: string; type: string; displayName: string; status: string; requestedAt: string; visit: { visitNumber: string; patient: Omit<PatientRef, "id"> } }[] } };
const labels: Record<string, string> = { duplicateGroups: "Potential duplicate groups", missingContacts: "Missing primary contact", missingAge: "Missing age", missingConsent: "Missing electronic-record consent", incompleteVisits: "Visits open over 24 hours", delayedResults: "Results pending over 24 hours" };
export default function DataQualityPanel() {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState("");
  useEffect(() => { void jsonRequest<Data>("/api/admin/data-quality", undefined, "Data quality workbench could not be loaded").then(setData).catch(reason => setError(reason.message)); }, []);
  if (!data && !error) return <section className="card"><p>Scanning facility records…</p></section>;
  return <div className="embeddedWorkspace">{error && <div className="alert">{error}</div>}{data && <><section className="metricGrid">{Object.entries(data.summary).map(([key, value]) => <article className={`metric ${value ? "urgent" : ""}`} key={key}><span>{labels[key] || key}</span><strong>{value}</strong></article>)}</section>
    <section className="card"><div className="cardHead"><div><h2>Potential duplicate patients</h2><p>Review candidates manually. The workbench never merges or deletes patient records.</p></div></div><div className="queue compact">{data.issues.duplicates.map(group => <div className="row" key={group.key}><span className="dot"/><div><strong>{group.patients.map(item => item.fullName).join(" / ")}</strong><small>{group.patients.map(item => item.patientNumber).join(" · ")}</small></div><b>REVIEW</b></div>)}{!data.issues.duplicates.length && <p>No duplicate candidates found.</p>}</div></section>
    <div className="supplyGrid"><QualityList title="Patient demographics and consent" rows={[...data.issues.missingContacts.map(item => ({ key: `contact-${item.id}`, title: item.fullName, detail: `${item.patientNumber} · missing primary contact` })), ...data.issues.missingAge.map(item => ({ key: `age-${item.id}`, title: item.fullName, detail: `${item.patientNumber} · missing date of birth or estimated age` })), ...data.issues.missingConsent.map(item => ({ key: `consent-${item.id}`, title: item.fullName, detail: `${item.patientNumber} · electronic-record consent not active` }))]}/><QualityList title="Incomplete operational records" rows={[...data.issues.incompleteVisits.map(item => ({ key: item.id, title: `${item.visitNumber} · ${item.patient.fullName}`, detail: `${item.status.replaceAll("_", " ")} · ${item.flags.join(", ").replaceAll("_", " ") || "open over 24 hours"}` })), ...data.issues.delayedResults.map(item => ({ key: item.id, title: `${item.visit.visitNumber} · ${item.displayName}`, detail: `${item.type} · ${item.status.replaceAll("_", " ")} · pending over 24 hours` }))]}/></div>
  </>}</div>;
}
function QualityList({ title, rows }: { title: string; rows: { key: string; title: string; detail: string }[] }) { return <section className="card"><div className="cardHead"><div><h2>{title}</h2><p>Resolve in the owning clinical or administrative workstation.</p></div><strong>{rows.length}</strong></div><div className="queue compact">{rows.slice(0, 30).map(item => <div className="row" key={item.key}><span className="dot"/><div><strong>{item.title}</strong><small>{item.detail}</small></div></div>)}{!rows.length && <p>No current issues.</p>}</div></section>; }
