"use client";
import { useEffect, useState } from "react";
import { jsonRequest } from "@/lib/client-http";

type Forecast = { code: string; name: string; available: number; consumed: number; dailyUse: number; daysOfStock: number | null; suggestedOrder: number; expiringWithin30: number; status: string };
export default function InventoryForecastPanel() {
  const [days, setDays] = useState(90); const [rows, setRows] = useState<Forecast[]>([]); const [error, setError] = useState("");
  useEffect(() => { void jsonRequest<{ forecasts: Forecast[] }>(`/api/inventory/forecast?days=${days}`, undefined, "Stock forecast could not be generated").then(data => setRows(data.forecasts)).catch(reason => setError(reason.message)); }, [days]);
  return <><header><div><p className="eyebrow">Inventory intelligence</p><h1>Forecast and reorder worklist</h1><p>Uses recorded dispensing consumption; suggestions support review and never create purchase orders automatically.</p></div><label>Consumption window<select value={days} onChange={event => setDays(Number(event.target.value))}><option value={30}>30 days</option><option value={90}>90 days</option><option value={180}>180 days</option></select></label></header>{error && <div className="alert">{error}</div>}<section className="card"><div className="cardHead"><div><h2>Stock outlook</h2><p>Critical ≤14 days; low ≤30 days. Slow moving means stock exists but no use was recorded in the selected window.</p></div><strong>{rows.filter(row => ["STOCK_OUT", "CRITICAL", "LOW"].includes(row.status)).length} action item(s)</strong></div><table className="reportResults"><thead><tr><th>Medicine</th><th>Status</th><th>Available</th><th>Consumed</th><th>Days left</th><th>Expiring 30d</th><th>Suggested order</th></tr></thead><tbody>{rows.map(row => <tr key={row.code}><td><strong>{row.name}</strong><small>{row.code}</small></td><td><span className={`statusPill ${row.status === "HEALTHY" ? "done" : "waiting"}`}>{row.status.replaceAll("_", " ")}</span></td><td>{row.available.toLocaleString()}</td><td>{row.consumed.toLocaleString()}</td><td>{row.daysOfStock ?? "No use"}</td><td>{row.expiringWithin30.toLocaleString()}</td><td><strong>{row.suggestedOrder.toLocaleString()}</strong></td></tr>)}</tbody></table></section></>;
}
