"use client";
import { useEffect, useMemo, useState } from "react";
import { jsonRequest } from "@/lib/client-http";

type Item = { id: string; code: string; name: string; reorderLevel?: string | null; unitOfMeasure?: string | null; inventoryBatches: { id: string; batchNumber: string; expiryDate: string; quantityAvailable: string; locationBalances: { quantity: string; store: { name: string } }[] }[] };

export default function InventoryWorkstation() {
  const [items, setItems] = useState<Item[]>([]); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [status, setStatus] = useState<"ALL" | "LOW" | "AVAILABLE" | "EMPTY">("ALL");
  useEffect(() => { void jsonRequest<{ items: Item[] }>("/api/inventory", undefined, "Inventory could not be loaded").then(data => setItems(data.items)).catch(reason => setError(reason.message)); }, []);
  const visible = useMemo(() => items.filter(item => { const available = item.inventoryBatches.reduce((sum, batch) => sum + Number(batch.quantityAvailable), 0); const low = item.reorderLevel != null && available <= Number(item.reorderLevel); const text = `${item.name} ${item.code} ${item.inventoryBatches.map(batch => batch.batchNumber).join(" ")}`.toLowerCase(); return text.includes(query.trim().toLowerCase()) && (status === "ALL" || (status === "LOW" && low) || (status === "AVAILABLE" && available > 0) || (status === "EMPTY" && available === 0)); }), [items, query, status]);
  return <><header><div><p className="eyebrow">Pharmacy inventory</p><h1>Batch and expiry stock control</h1><p>Monitor balances by batch and store. Goods receipt is controlled from approved purchase orders in Supply chain.</p></div></header>{error && <div className="alert">{error}</div>}<section className="card compact"><div className="cardHead"><div><h2>Available stock</h2><p>Search by medicine, code or batch. Filter items needing attention.</p></div><strong>{visible.length} shown</strong></div><div className="inventorySearch"><input type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search medicine, item code or batch number…" aria-label="Search inventory"/><select value={status} onChange={event => setStatus(event.target.value as typeof status)} aria-label="Filter inventory status"><option value="ALL">All stock</option><option value="LOW">Reorder needed</option><option value="AVAILABLE">In stock</option><option value="EMPTY">No usable stock</option></select></div><div className="queue">{visible.map(item => { const available = item.inventoryBatches.reduce((sum, batch) => sum + Number(batch.quantityAvailable), 0); const reorder = item.reorderLevel != null && available <= Number(item.reorderLevel); return <div className={`row ${reorder ? "urgent" : ""}`} key={item.id}><span className="dot"/><div><strong>{item.name}</strong><small>{item.code} · {item.inventoryBatches.length ? item.inventoryBatches.map(batch => `${batch.batchNumber}: ${Number(batch.quantityAvailable)} · ${batch.locationBalances.map(balance => `${balance.store.name} ${Number(balance.quantity)}`).join(", ")} · exp ${new Date(batch.expiryDate).toLocaleDateString()}`).join(" | ") : "No usable batches"}</small></div><b>{available} {item.unitOfMeasure || "units"}</b><time>{reorder ? "REORDER" : available > 0 ? "IN STOCK" : "NO STOCK"}</time></div>; })}{!visible.length && <div className="empty"><strong>No matching stock</strong><p>Change the search or stock-status filter.</p></div>}</div></section></>;
}
