"use client";
import { FormEvent, useEffect, useState } from "react";
import { jsonRequest } from "@/lib/client-http";
type Data = { suppliers: any[]; stores: any[]; purchaseOrders: any[]; items: any[]; batches: any[] };
const empty: Data = { suppliers: [], stores: [], purchaseOrders: [], items: [], batches: [] };
export default function SupplyWorkstation() {
  const [data, setData] = useState<Data>(empty); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { setData(await jsonRequest<Data>("/api/supply", undefined, "Supply-chain data could not be loaded")); }
  useEffect(() => { void load().catch(reason => setError(reason.message)); }, []);
  async function submit(event: FormEvent<HTMLFormElement>, action: string) { event.preventDefault(); setBusy(true); setError(""); setNotice(""); const form = new FormData(event.currentTarget); const body = Object.fromEntries([...form.entries()].filter(([, value]) => value !== "")); try { await jsonRequest("/api/supply", { method: "POST", body: JSON.stringify({ action, ...body }) }, "Supply-chain transaction could not be saved"); setNotice(`${action.replaceAll("_", " ").toLowerCase()} recorded successfully.`); event.currentTarget.reset(); await load(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  const openLines = data.purchaseOrders.filter(order => order.status !== "RECEIVED").flatMap(order => order.lines.map((line: any) => ({ ...line, orderNumber: order.orderNumber })));
  return <><header><div><p className="eyebrow">Procurement & logistics</p><h1>Supply chain control</h1><p>Order, receive, count and transfer medicines with batch-level traceability.</p></div></header>{error && <div className="alert">{error}</div>}{notice && <div className="alert success">{notice}</div>}
  <section className="card"><div className="cardHead"><div><h2>Open purchase orders</h2><p>Approved orders awaiting complete receipt.</p></div><strong>{openLines.length}</strong></div><div className="queue">{openLines.map(line => <div className="row" key={line.id}><span className="dot"/><div><strong>{line.orderNumber}</strong><small>{data.items.find(item => item.id === line.catalogItemId)?.name || line.catalogItemId}</small></div><b>{Number(line.quantityReceived)} / {Number(line.quantityOrdered)}</b></div>)}</div></section>
  <div className="supplyGrid"><form className="card dataForm" onSubmit={event => submit(event, "SUPPLIER")}><h2 className="wide">Add supplier</h2><label>Code *<input name="code" required/></label><label>Name *<input name="name" required/></label><label>Phone<input name="phone"/></label><label>Email<input name="email" type="email"/></label><button className="primary wide" disabled={busy}>Save supplier</button></form>
  <form className="card dataForm" onSubmit={event => submit(event, "STORE")}><h2 className="wide">Add store</h2><label>Code *<input name="code" required/></label><label>Name *<input name="name" required/></label><button className="primary wide" disabled={busy}>Save store</button></form>
  <form className="card dataForm" onSubmit={event => submit(event, "PURCHASE_ORDER")}><h2 className="wide">Create purchase order</h2><label>Supplier *<select name="supplierId" required><option value="">Select</option>{data.suppliers.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Medicine *<select name="catalogItemId" required><option value="">Select</option>{data.items.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Quantity *<input name="quantity" type="number" min="0.001" step="0.001" required/></label><label>Unit cost<input name="unitCost" type="number" min="0" step="0.01"/></label><label>Expected date<input name="expectedAt" type="date"/></label><label>Note<input name="notes"/></label><button className="primary wide" disabled={busy}>Approve purchase order</button></form>
  <form className="card dataForm" onSubmit={event => submit(event, "RECEIVE")}><h2 className="wide">Receive against PO (GRN)</h2><label>PO line *<select name="lineId" required><option value="">Select</option>{openLines.map(line => <option value={line.id} key={line.id}>{line.orderNumber} · {data.items.find(item => item.id === line.catalogItemId)?.name}</option>)}</select></label><label>Store *<select name="storeId" required>{data.stores.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Batch *<input name="batchNumber" required/></label><label>Expiry *<input name="expiryDate" type="date" required/></label><label>Quantity received *<input name="quantity" type="number" min="0.001" step="0.001" required/></label><button className="primary wide" disabled={busy}>Post GRN</button></form>
  <form className="card dataForm" onSubmit={event => submit(event, "COUNT")}><h2 className="wide">Stock count</h2><label>Store *<select name="storeId" required>{data.stores.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Batch *<select name="batchId" required>{data.batches.map(item => <option value={item.id} key={item.id}>{item.catalogItem.name} · {item.batchNumber}</option>)}</select></label><label>Counted quantity *<input name="countedQuantity" type="number" min="0" step="0.001" required/></label><label>Variance reason *<input name="reason" minLength={5} required/></label><button className="primary wide" disabled={busy}>Post count variance</button></form>
  <form className="card dataForm" onSubmit={event => submit(event, "TRANSFER")}><h2 className="wide">Transfer stock</h2><label>Source *<select name="sourceStoreId" required>{data.stores.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Destination *<select name="destinationStoreId" required>{data.stores.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Batch *<select name="batchId" required>{data.batches.map(item => <option value={item.id} key={item.id}>{item.catalogItem.name} · {item.batchNumber}</option>)}</select></label><label>Quantity *<input name="quantity" type="number" min="0.001" step="0.001" required/></label><label className="wide">Reason *<input name="reason" minLength={5} required/></label><button className="primary wide" disabled={busy}>Transfer stock</button></form></div></>;
}
