<?php
require __DIR__.'/api/feedback.php';content_tables();
if(isset($_GET['id'])){
    $id=filter_var($_GET['id'],FILTER_VALIDATE_INT);$row=$id?(rows(run("SELECT * FROM posts WHERE id=? AND published IS NOT NULL AND published!=''",[$id]))[0]??null):null;
    if(!$row){http_response_code(404);public_content('Post unavailable','<section class="wrap page-head"><h1>This post is unavailable.</h1><a href="/blog.php">Browse facility updates</a></section>',config()['origin'].'/blog.php');exit;}
    $p=json_decode($row['published'],true);$p['id']=$id;public_content($p['title'],'<nav class="wrap section-tabs"><a href="/blog.php">← All facility updates</a></nav>'.render_article($p).blog_comments((int)$id),config()['origin'].'/blog.php?id='.$id,$p['summary']?:substr($p['body'],0,160),$p);exit;
}
$q=is_string($_GET['q']??null)?substr(trim($_GET['q']),0,100):'';$category=is_string($_GET['category']??null)?substr($_GET['category'],0,80):'';$page=max(1,(int)($_GET['page']??1));
$all=rows(run("SELECT id,published,published_at FROM posts WHERE published IS NOT NULL AND published!='' ORDER BY published_at DESC,id DESC"));$matches=[];$cats=[];
foreach($all as $row){$p=json_decode($row['published'],true);$cats[$p['category']]=true;if(($category===''||$category===$p['category'])&&($q===''||stripos($p['title'].' '.$p['summary'].' '.$p['body'],$q)!==false))$matches[]=[$row,$p];}
$page=min($page,max(1,(int)ceil(count($matches)/9)));ob_start(); ?>
<section class="wrap page-head"><p class="eyebrow">FACILITY BLOG</p><h1>News from <em>Mwein.</em></h1><p class="lead">Facility updates, community stories and useful resources from our team.</p><form method="get" class="filter"><label>Search updates<input name="q" value="<?= h($q) ?>" maxlength="100" placeholder="Search by topic"></label><label>Category<select name="category"><option value="">All categories</option><?php foreach(array_keys($cats) as $cat): ?><option <?= $cat===$category?'selected':'' ?>><?= h($cat) ?></option><?php endforeach ?></select></label><button class="button">Search</button></form></section>
<section class="wrap post-grid"><?php foreach(array_slice($matches,($page-1)*9,9) as [$row,$p]): ?><article class="contact-card"><?php if(!empty($p['media_ids'])):$m=rows(run('SELECT alt FROM media WHERE id=?',[(int)post_images($p)[0]]))[0]??null;if($m): ?><img class="post-image" loading="lazy" src="/media.php?id=<?= (int)post_images($p)[0] ?>" alt="<?= h($m['alt']) ?>"><?php endif;endif ?><p class="eyebrow"><?= h($p['category']) ?> · <?= h(date('j M Y',strtotime($row['published_at']))) ?></p><h2><a href="/blog.php?id=<?= (int)$row['id'] ?>"><?= h($p['title']) ?></a></h2><p><?= h($p['summary']) ?></p><a href="/blog.php?id=<?= (int)$row['id'] ?>">Read update →</a></article><?php endforeach ?><?php if(!$matches): ?><p>No updates match this search. <a href="/blog.php">See all updates</a>.</p><?php endif ?></section><nav class="wrap pagination"><span>Page <?= $page ?> of <?= max(1,(int)ceil(count($matches)/9)) ?></span><?php if($page>1): ?><a href="?<?= h(http_build_query(['q'=>$q,'category'=>$category,'page'=>$page-1])) ?>">Previous</a><?php endif ?><?php if($page*9<count($matches)): ?><a href="?<?= h(http_build_query(['q'=>$q,'category'=>$category,'page'=>$page+1])) ?>">Next →</a><?php endif ?></nav>
<?php public_content('Facility blog',ob_get_clean(),config()['origin'].'/blog.php'); ?>
