<?php
require __DIR__.'/api/feedback.php';feedback_tables();
$summary=rows(run("SELECT COUNT(*) AS count,AVG(rating) AS average FROM feedback WHERE kind='review' AND status='approved'"))[0];
$page=max(1,(int)($_GET['page']??1));$pages=max(1,(int)ceil($summary['count']/10));$page=min($page,$pages);
$items=rows(run("SELECT * FROM feedback WHERE kind='review' AND status='approved' ORDER BY id DESC LIMIT 10 OFFSET ?",[($page-1)*10]));ob_start(); ?>
<section class="wrap page-head"><p class="eyebrow">YOUR VOICE MATTERS</p><h1>Experiences at <em>Mwein.</em></h1><p class="lead">Share your experience of visiting our clinic, or read feedback from other website visitors.</p><div class="review-summary"><?php if($summary['count']): ?><strong><?= h(number_format((float)$summary['average'],1)) ?> <small>/ 5</small></strong><span>From <?= (int)$summary['count'] ?> published <?= (int)$summary['count']===1?'review':'reviews' ?></span><?php else: ?><strong>No ratings yet</strong><span>Be the first to share your experience.</span><?php endif ?></div><p class="small">Reviews submitted through this website are moderated and are not independently verified as patient visits. The average includes all published star ratings, including critical reviews.</p><a class="button" href="#leave-review">Write a review ↓</a></section>
<section class="wrap feedback-section" aria-label="Published visitor reviews"><?= feedback_cards($items) ?><?php if(!$items): ?><p>No published reviews yet.</p><?php endif ?><?php if($pages>1): ?><nav class="pagination" aria-label="Review pages"><span>Page <?= $page ?> of <?= $pages ?></span><?php if($page>1): ?><a href="?page=<?= $page-1 ?>">Previous</a><?php endif ?><?php if($page<$pages): ?><a href="?page=<?= $page+1 ?>">Next</a><?php endif ?></nav><?php endif ?></section>
<section class="wrap feedback-section" id="leave-review"><p class="eyebrow">HELP US IMPROVE</p><h2>How was your visit?</h2><?= feedback_form('review') ?></section>
<?php public_content('Visitor reviews',ob_get_clean(),config()['origin'].'/reviews.php'); ?>
